language: python
matrix:
  include:
    - addons:
        apt:
          upgrade: true
          packages: python3.8-minimal
    - addons:
        apt:
          upgrade: true
          packages: libpython3.8-minimal
    - addons:
        apt:
          upgrade: true
          packages: libpython3.8-stdlib
    - addons:
        apt:
          upgrade: true
          packages: python3-lib2to3
install: true
script: true
